apiVersion: v1
kind: Service
metadata:
  namespace: log-app
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5000