apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-app
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: ddeeh/k8s_pingpong
          env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
                path: /pingpong
                port: 5000