apiVersion: v1
kind: Service
metadata:
  namespace: log-app
  name: pingpong-svc
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000