apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/backend-deployment.yaml
  - manifests/backend-service.yaml
  - manifests/frontend-deployment.yaml
  - manifests/frontend-service.yaml
  - manifests/dbservice.yaml
  - manifests/ingress.yaml
  - manifests/namespaces.yaml
  - manifests/statefulset.yaml
  - manifests/todojob.yaml
images:
  - name: PROJECT/BACKEND_IMAGE
    newName: ddeeh/k8s_todo
  - name: PROJECT/FRONTEND_IMAGE
    newName: ddeeh/v2_front