apiVersion: v1
kind: Service
metadata:
  namespace: todo-app
  name: todo-svc
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000