apiVersion: v1
kind: Service
metadata:
  namespace: todo-app
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5000