apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-app
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: PROJECT/BACKEND_IMAGE
          command: ["/bin/sh"]
          args: ["-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
          env:
          - name: POSTGRES_USERNAME
            value: ${{ secrets.POSTGRES_USERNAME }}
          - name: POSTGRES_PASSWORD
            value: ${{ secrets.POSTGRES_PASSWORD }}